services:

    #
    # Recipient field
    #
    fos_message.fields.fos_user_recipient:
        class: FOS\MessageBundle\Bridge\FOSUser\Field\FOSUserRecipientFieldType
        arguments:
            - @fos_user.user_to_username_transformer
        tags:
            - { name: form.type, alias: fos_user_recipient }